name: GoReleaser

on:
  push:
    tags:
      - 'v*'  # Trigger on tags that start with 'v'
  workflow_dispatch:  # Manual trigger

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.22.1'

      - name: Install GoReleaser
        run: |
          curl -sfL https://install.goreleaser.com/github.com/goreleaser/goreleaser.sh | sh -s -- -b $(go env GOPATH)/bin v0.176.0

      - name: Run GoReleaser
        run: |
          goreleaser release --rm-dist

      - name: Upload Artifacts
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: release-artifacts
          path: dist/
