name: Release

on:
  workflow_dispatch: { }  # Triggered manually

jobs:
  release:
    name: Release
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.3.0'

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.1'

      - name: Install dependencies
        run: go mod tidy

      - name: Build project
        run: go build ./...

      - name: Test project
        run: go test ./...

      - run: npx semantic-release
        env:
          # Added Personal Access Token, or it won't trigger other events
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_SEMANTIC_RELEASE }}